.PHONY: init
init:
	terraform init

.PHONY: fmt
fmt:
	terraform fmt -recursive

.PHONY: validate
validate:
	terraform validate

.PHONY: plan
plan:
	terraform plan

.PHONY: apply
apply:
	terraform apply

.PHONY: console
console:
	terraform console